version: '3'

services:
  api:
    image: node:18-alpine
    working_dir: /api
    ports:
      - 8000:8000 
    command: sh -c 'npm install && npm install --dev && npm run api'
    environment:
      - PORT=8000
      - ORIGIN_URL=app:5000
      - MONGO_URL=mongodb://mongodibi:27017/lucifer
    volumes:
      - ../../api:/api

  app:
    image: node:18-alpine
    working_dir: /app
    command: sh -c 'npm install && npm install --dev && npm run dev'
    ports:
      - 5000:5000
    environment:
      - API_URL=api:8000
    volumes:
      - ./:/app

  mongodibi:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=lucifer
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
